{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting pycaret\n",
      "  Using cached pycaret-2.3.6-py3-none-any.whl (301 kB)\n",
      "Requirement already satisfied: pyyaml<6.0.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pycaret) (5.4.1)\n",
      "Collecting mlxtend>=0.17.0\n",
      "  Using cached mlxtend-0.19.0-py2.py3-none-any.whl (1.3 MB)\n",
      "Collecting kmodes>=0.10.1\n",
      "  Using cached kmodes-0.11.1-py2.py3-none-any.whl (19 kB)\n",
      "Collecting umap-learn\n",
      "  Using cached umap_learn-0.5.2-py3-none-any.whl\n",
      "Requirement already satisfied: yellowbrick>=1.0.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pycaret) (1.3.post1)\n",
      "Collecting wordcloud\n",
      "  Using cached wordcloud-1.8.1.tar.gz (220 kB)\n",
      "Requirement already satisfied: scipy<=1.5.4 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pycaret) (1.5.4)\n",
      "Collecting pyLDAvis\n",
      "  Using cached pyLDAvis-3.3.1.tar.gz (1.7 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'done'\n",
      "  Installing backend dependencies: started"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\python.exe' 'C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-standalone-pip-zfacx_gp\\__env_pip__.zip\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-build-env-zybrwu8h\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.28.5' 'numpy==1.13.3; python_version=='\"'\"'3.6'\"'\"' and platform_system!='\"'\"'AIX'\"'\"' and platform_python_implementation == '\"'\"'CPython'\"'\"'' 'numpy==1.14.0; python_version=='\"'\"'3.6'\"'\"' and platform_system!='\"'\"'AIX'\"'\"' and platform_python_implementation != '\"'\"'CPython'\"'\"'' 'numpy==1.14.5; python_version=='\"'\"'3.7'\"'\"' and platform_system!='\"'\"'AIX'\"'\"'' 'numpy==1.17.3; python_version>='\"'\"'3.8'\"'\"' and platform_system!='\"'\"'AIX'\"'\"'' 'numpy==1.16.0; python_version=='\"'\"'3.6'\"'\"' and platform_system=='\"'\"'AIX'\"'\"'' 'numpy==1.16.0; python_version=='\"'\"'3.7'\"'\"' and platform_system=='\"'\"'AIX'\"'\"'' 'numpy==1.17.3; python_version>='\"'\"'3.8'\"'\"' and platform_system=='\"'\"'AIX'\"'\"'' 'scipy>=0.19.1'\n",
      "       cwd: None\n",
      "  Complete output (671 lines):\n",
      "  Ignoring numpy: markers 'python_version == \"3.6\" and platform_system != \"AIX\" and platform_python_implementation == \"CPython\"' don't match your environment\n",
      "  Ignoring numpy: markers 'python_version == \"3.6\" and platform_system != \"AIX\" and platform_python_implementation != \"CPython\"' don't match your environment\n",
      "  Ignoring numpy: markers 'python_version == \"3.7\" and platform_system != \"AIX\"' don't match your environment\n",
      "  Ignoring numpy: markers 'python_version == \"3.6\" and platform_system == \"AIX\"' don't match your environment\n",
      "  Ignoring numpy: markers 'python_version == \"3.7\" and platform_system == \"AIX\"' don't match your environment\n",
      "  Ignoring numpy: markers 'python_version >= \"3.8\" and platform_system == \"AIX\"' don't match your environment\n",
      "  Collecting setuptools\n",
      "    Using cached setuptools-60.5.0-py3-none-any.whl (958 kB)\n",
      "  Collecting wheel\n",
      "    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)\n",
      "  Collecting Cython>=0.28.5\n",
      "    Using cached Cython-0.29.26-py2.py3-none-any.whl (983 kB)\n",
      "  Collecting numpy==1.17.3\n",
      "    Using cached numpy-1.17.3.zip (6.4 MB)\n",
      "  Collecting scipy>=0.19.1\n",
      "    Using cached scipy-1.7.3-cp39-cp39-win_amd64.whl (34.3 MB)\n",
      "  Building wheels for collected packages: numpy\n",
      "    Building wheel for numpy (setup.py): started\n",
      "    Building wheel for numpy (setup.py): finished with status 'error'\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\Data Scientist\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ymbyaqa2\\\\numpy_809048c662404d26b78660070e772f5f\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\Data Scientist\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ymbyaqa2\\\\numpy_809048c662404d26b78660070e772f5f\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' bdist_wheel -d 'C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-wheel-8vf_r7qn'\n",
      "         cwd: C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-ymbyaqa2\\numpy_809048c662404d26b78660070e772f5f\\\n",
      "    Complete output (305 lines):\n",
      "    Running from numpy source directory.\n",
      "    blas_opt_info:\n",
      "    blas_mkl_info:\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries mkl_rt not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "      NOT AVAILABLE\n",
      "  \n",
      "    blis_info:\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries blis not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "      NOT AVAILABLE\n",
      "  \n",
      "    openblas_info:\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries openblas not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "    get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'\n",
      "    customize GnuFCompiler\n",
      "    Could not locate executable g77\n",
      "    Could not locate executable f77\n",
      "    customize IntelVisualFCompiler\n",
      "    Could not locate executable ifort\n",
      "    Could not locate executable ifl\n",
      "    customize AbsoftFCompiler\n",
      "    Could not locate executable f90\n",
      "    customize CompaqVisualFCompiler\n",
      "    Could not locate executable DF\n",
      "    customize IntelItaniumVisualFCompiler\n",
      "    Could not locate executable efl\n",
      "    customize Gnu95FCompiler\n",
      "    Could not locate executable gfortran\n",
      "    Could not locate executable f95\n",
      "    customize G95FCompiler\n",
      "    Could not locate executable g95\n",
      "    customize IntelEM64VisualFCompiler\n",
      "    customize IntelEM64TFCompiler\n",
      "    Could not locate executable efort\n",
      "    Could not locate executable efc\n",
      "    customize PGroupFlangCompiler\n",
      "    Could not locate executable flang\n",
      "    don't know how to compile Fortran code on platform 'nt'\n",
      "      NOT AVAILABLE\n",
      "  \n",
      "    atlas_3_10_blas_threads_info:\n",
      "    Setting PTATLAS=ATLAS\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries tatlas not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "      NOT AVAILABLE\n",
      "  \n",
      "    atlas_3_10_blas_info:\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries satlas not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "      NOT AVAILABLE\n",
      "  \n",
      "    atlas_blas_threads_info:\n",
      "    Setting PTATLAS=ATLAS\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries ptf77blas,ptcblas,atlas not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "      NOT AVAILABLE\n",
      "  \n",
      "    atlas_blas_info:\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries f77blas,cblas,atlas not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "      NOT AVAILABLE\n",
      "  \n",
      "    accelerate_info:\n",
      "      NOT AVAILABLE\n",
      "  \n",
      "    blas_info:\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries blas not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "      NOT AVAILABLE\n",
      "  \n",
      "    blas_src_info:\n",
      "      NOT AVAILABLE\n",
      "  \n",
      "      NOT AVAILABLE\n",
      "  \n",
      "    'svnversion' is not recognized as an internal or external command,\n",
      "    operable program or batch file.\n",
      "    non-existing path in 'numpy\\\\distutils': 'site.cfg'\n",
      "    lapack_opt_info:\n",
      "    lapack_mkl_info:\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries mkl_rt not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "  Installing backend dependencies: finished with status 'done'\n",
      "    Preparing wheel metadata: started\n",
      "    Preparing wheel metadata: finished with status 'done'\n",
      "Requirement already satisfied: lightgbm>=2.3.1 in c:\\users\\data scientist\\appdata\\roaming\\python\\python39\\site-packages (from pycaret) (3.3.2)\n",
      "Collecting mlflow\n",
      "  Using cached mlflow-1.23.0-py3-none-any.whl (15.6 MB)\n",
      "Requirement already satisfied: joblib in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pycaret) (1.0.1)\n",
      "Requirement already satisfied: ipywidgets in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pycaret) (7.6.5)\n",
      "Collecting pandas-profiling>=2.8.0\n",
      "  Using cached pandas_profiling-3.1.0-py2.py3-none-any.whl (261 kB)\n",
      "Collecting imbalanced-learn==0.7.0\n",
      "  Using cached imbalanced_learn-0.7.0-py3-none-any.whl (167 kB)\n",
      "Collecting cufflinks>=0.17.0\n",
      "  Using cached cufflinks-0.17.3-py3-none-any.whl\n",
      "Requirement already satisfied: matplotlib in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pycaret) (3.5.1)\n",
      "Collecting scikit-plot\n",
      "  Using cached scikit_plot-0.3.7-py3-none-any.whl (33 kB)\n",
      "Requirement already satisfied: plotly>=4.4.1 in c:\\users\\data scientist\\appdata\\roaming\\python\\python39\\site-packages (from pycaret) (5.5.0)\n",
      "Collecting gensim<4.0.0\n",
      "  Using cached gensim-3.8.3.tar.gz (23.4 MB)\n",
      "Requirement already satisfied: nltk in c:\\users\\data scientist\\appdata\\roaming\\python\\python39\\site-packages (from pycaret) (3.6.7)\n",
      "Collecting textblob\n",
      "  Using cached textblob-0.17.1-py2.py3-none-any.whl (636 kB)\n",
      "Requirement already satisfied: seaborn in c:\\users\\data scientist\\appdata\\roaming\\python\\python39\\site-packages (from pycaret) (0.11.2)\n",
      "Collecting pyod\n",
      "  Using cached pyod-0.9.7-py3-none-any.whl\n",
      "Collecting scikit-learn==0.23.2\n",
      "  Using cached scikit-learn-0.23.2.tar.gz (7.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "Collecting pycaret\n",
      "  Using cached pycaret-2.3.5-py3-none-any.whl (288 kB)\n",
      "Requirement already satisfied: numpy==1.19.5 in c:\\users\\data scientist\\appdata\\roaming\\python\\python39\\site-packages (from pycaret) (1.19.5)\n",
      "  Using cached pycaret-2.3.4-py3-none-any.whl (266 kB)\n",
      "Collecting numba<0.54\n",
      "  Downloading numba-0.53.1-cp39-cp39-win_amd64.whl (2.3 MB)\n",
      "Collecting pycaret\n",
      "  Using cached pycaret-2.3.3-py3-none-any.whl (264 kB)\n",
      "  Using cached pycaret-2.3.2-py3-none-any.whl (263 kB)\n",
      "  Using cached pycaret-2.3.1-py3-none-any.whl (261 kB)\n",
      "  Using cached pycaret-2.3.0-py3-none-any.whl (261 kB)\n",
      "Collecting gensim\n",
      "  Using cached gensim-4.1.2-cp39-cp39-win_amd64.whl (24.0 MB)\n",
      "Collecting imbalanced-learn>=0.7.0\n",
      "  Using cached imbalanced_learn-0.9.0-py3-none-any.whl (199 kB)\n",
      "Collecting pycaret\n",
      "  Using cached pycaret-2.2.3-py3-none-any.whl (249 kB)\n",
      "Requirement already satisfied: catboost>=0.23.2 in c:\\users\\data scientist\\appdata\\roaming\\python\\python39\\site-packages (from pycaret) (1.0.4)\n",
      "Collecting spacy\n",
      "  Using cached spacy-3.2.1-cp39-cp39-win_amd64.whl (11.8 MB)\n",
      "Collecting pycaret\n",
      "  Using cached pycaret-2.2.2-py3-none-any.whl (249 kB)\n",
      "Requirement already satisfied: scikit-learn>=0.23.2 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pycaret) (1.0.2)\n",
      "Requirement already satisfied: pandas in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pycaret) (1.4.0)\n",
      "Requirement already satisfied: xgboost>=1.1.0 in c:\\users\\data scientist\\appdata\\roaming\\python\\python39\\site-packages (from pycaret) (1.2.1)\n",
      "Requirement already satisfied: IPython in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pycaret) (8.0.1)\n",
      "Requirement already satisfied: graphviz in c:\\users\\data scientist\\appdata\\roaming\\python\\python39\\site-packages (from catboost>=0.23.2->pycaret) (0.19.1)\n",
      "Requirement already satisfied: six in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from catboost>=0.23.2->pycaret) (1.16.0)\n",
      "Requirement already satisfied: colorlover>=0.2.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from cufflinks>=0.17.0->pycaret) (0.3.0)\n",
      "Requirement already satisfied: setuptools>=34.4.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from cufflinks>=0.17.0->pycaret) (58.0.4)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from imbalanced-learn>=0.7.0->pycaret) (3.0.0)\n",
      "Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from IPython->pycaret) (3.0.24)\n",
      "Requirement already satisfied: traitlets>=5 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from IPython->pycaret) (5.1.1)\n",
      "Requirement already satisfied: stack-data in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from IPython->pycaret) (0.1.4)\n",
      "Requirement already satisfied: jedi>=0.16 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from IPython->pycaret) (0.18.1)\n",
      "Requirement already satisfied: pickleshare in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from IPython->pycaret) (0.7.5)\n",
      "Requirement already satisfied: black in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from IPython->pycaret) (21.12b0)\n",
      "Requirement already satisfied: pygments in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from IPython->pycaret) (2.11.2)\n",
      "Requirement already satisfied: matplotlib-inline in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from IPython->pycaret) (0.1.3)\n",
      "Requirement already satisfied: colorama in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from IPython->pycaret) (0.4.4)\n",
      "Requirement already satisfied: decorator in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from IPython->pycaret) (5.1.1)\n",
      "Requirement already satisfied: backcall in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from IPython->pycaret) (0.2.0)\n",
      "Requirement already satisfied: ipykernel>=4.5.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from ipywidgets->pycaret) (6.7.0)\n",
      "Requirement already satisfied: widgetsnbextension~=3.5.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from ipywidgets->pycaret) (3.5.2)\n",
      "Requirement already satisfied: ipython-genutils~=0.2.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from ipywidgets->pycaret) (0.2.0)\n",
      "Requirement already satisfied: jupyterlab-widgets>=1.0.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from ipywidgets->pycaret) (1.0.2)\n",
      "Requirement already satisfied: nbformat>=4.2.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from ipywidgets->pycaret) (5.1.3)\n",
      "Requirement already satisfied: tornado<7.0,>=4.2 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (6.1)\n",
      "Requirement already satisfied: jupyter-client<8.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (7.1.2)\n",
      "Requirement already satisfied: debugpy<2.0,>=1.0.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (1.5.1)\n",
      "Requirement already satisfied: nest-asyncio in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (1.5.4)\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from jedi>=0.16->IPython->pycaret) (0.8.3)\n",
      "Requirement already satisfied: entrypoints in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets->pycaret) (0.3)\n",
      "Requirement already satisfied: jupyter-core>=4.6.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets->pycaret) (4.9.1)\n",
      "Requirement already satisfied: python-dateutil>=2.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets->pycaret) (2.8.2)\n",
      "Requirement already satisfied: pyzmq>=13 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets->pycaret) (22.3.0)\n",
      "Requirement already satisfied: pywin32>=1.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from jupyter-core>=4.6.0->jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets->pycaret) (227)\n",
      "Requirement already satisfied: wheel in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from lightgbm>=2.3.1->pycaret) (0.37.1)\n",
      "Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from nbformat>=4.2.0->ipywidgets->pycaret) (4.4.0)\n",
      "Requirement already satisfied: attrs>=17.4.0 in c:\\users\\data scientist\\appdata\\roaming\\python\\python39\\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->pycaret) (21.4.0)\n",
      "Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->pycaret) (0.18.1)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pandas->pycaret) (2021.3)\n",
      "Requirement already satisfied: phik>=0.11.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pandas-profiling>=2.8.0->pycaret) (0.12.0)\n",
      "Requirement already satisfied: tqdm>=4.48.2 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pandas-profiling>=2.8.0->pycaret) (4.62.3)\n",
      "Requirement already satisfied: requests>=2.24.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pandas-profiling>=2.8.0->pycaret) (2.27.1)\n",
      "Requirement already satisfied: htmlmin>=0.1.12 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pandas-profiling>=2.8.0->pycaret) (0.1.12)\n",
      "Requirement already satisfied: tangled-up-in-unicode==0.1.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pandas-profiling>=2.8.0->pycaret) (0.1.0)\n",
      "Requirement already satisfied: jinja2>=2.11.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pandas-profiling>=2.8.0->pycaret) (3.0.3)\n",
      "Requirement already satisfied: visions[type_image_path]==0.7.4 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pandas-profiling>=2.8.0->pycaret) (0.7.4)\n",
      "Requirement already satisfied: missingno>=0.4.2 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pandas-profiling>=2.8.0->pycaret) (0.5.0)\n",
      "Requirement already satisfied: multimethod>=1.4 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pandas-profiling>=2.8.0->pycaret) (1.6)\n",
      "Requirement already satisfied: markupsafe~=2.0.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pandas-profiling>=2.8.0->pycaret) (2.0.1)\n",
      "Requirement already satisfied: pydantic>=1.8.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pandas-profiling>=2.8.0->pycaret) (1.8.2)\n",
      "Requirement already satisfied: networkx>=2.4 in c:\\users\\data scientist\\appdata\\roaming\\python\\python39\\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling>=2.8.0->pycaret) (2.6.3)\n",
      "Requirement already satisfied: Pillow in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling>=2.8.0->pycaret) (9.0.0)\n",
      "Requirement already satisfied: imagehash in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling>=2.8.0->pycaret) (4.2.1)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from matplotlib->pycaret) (1.3.2)\n",
      "Requirement already satisfied: pyparsing>=2.2.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from matplotlib->pycaret) (3.0.7)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from matplotlib->pycaret) (4.29.0)\n",
      "Requirement already satisfied: packaging>=20.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from matplotlib->pycaret) (21.3)\n",
      "Requirement already satisfied: cycler>=0.10 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from matplotlib->pycaret) (0.11.0)\n",
      "Requirement already satisfied: tenacity>=6.2.0 in c:\\users\\data scientist\\appdata\\roaming\\python\\python39\\site-packages (from plotly>=4.4.1->pycaret) (8.0.1)\n",
      "Requirement already satisfied: wcwidth in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->IPython->pycaret) (0.2.5)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pydantic>=1.8.1->pandas-profiling>=2.8.0->pycaret) (4.0.1)\n",
      "Requirement already satisfied: charset-normalizer~=2.0.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (2.0.10)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (2021.10.8)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (3.3)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (1.26.8)\n",
      "Requirement already satisfied: notebook>=4.4.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from widgetsnbextension~=3.5.0->ipywidgets->pycaret) (6.4.8)\n",
      "Requirement already satisfied: terminado>=0.8.3 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.12.1)\n",
      "Requirement already satisfied: nbconvert in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (6.4.0)\n",
      "Requirement already satisfied: prometheus-client in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.13.0)\n",
      "Requirement already satisfied: Send2Trash>=1.8.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (1.8.0)\n",
      "Requirement already satisfied: argon2-cffi in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (21.3.0)\n",
      "Requirement already satisfied: pywinpty>=1.1.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from terminado>=0.8.3->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (2.0.1)\n",
      "Requirement already satisfied: argon2-cffi-bindings in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (21.2.0)\n",
      "Requirement already satisfied: cffi>=1.0.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (1.15.0)\n",
      "Requirement already satisfied: pycparser in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (2.21)\n",
      "Requirement already satisfied: platformdirs>=2 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from black->IPython->pycaret) (2.4.1)\n",
      "Requirement already satisfied: pathspec<1,>=0.9.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from black->IPython->pycaret) (0.9.0)\n",
      "Requirement already satisfied: tomli<2.0.0,>=0.2.6 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from black->IPython->pycaret) (1.2.3)\n",
      "Requirement already satisfied: click>=7.1.2 in c:\\users\\data scientist\\appdata\\roaming\\python\\python39\\site-packages (from black->IPython->pycaret) (8.0.3)\n",
      "Requirement already satisfied: mypy-extensions>=0.4.3 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from black->IPython->pycaret) (0.4.3)\n",
      "Requirement already satisfied: Cython==0.29.23 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from gensim->pycaret) (0.29.23)\n",
      "Requirement already satisfied: smart-open>=1.8.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from gensim->pycaret) (5.2.1)\n",
      "Requirement already satisfied: PyWavelets in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from imagehash->visions[type_image_path]==0.7.4->pandas-profiling>=2.8.0->pycaret) (1.2.0)\n",
      "Requirement already satisfied: cloudpickle in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from mlflow->pycaret) (2.0.0)\n",
      "Requirement already satisfied: querystring-parser in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from mlflow->pycaret) (1.2.4)\n",
      "Requirement already satisfied: protobuf>=3.7.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from mlflow->pycaret) (3.19.3)\n",
      "Requirement already satisfied: databricks-cli>=0.8.7 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from mlflow->pycaret) (0.16.2)\n",
      "Requirement already satisfied: sqlalchemy in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from mlflow->pycaret) (1.4.31)\n",
      "Requirement already satisfied: importlib-metadata!=4.7.0,>=3.7.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from mlflow->pycaret) (4.10.1)\n",
      "Requirement already satisfied: sqlparse>=0.3.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from mlflow->pycaret) (0.4.2)\n",
      "Requirement already satisfied: Flask in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from mlflow->pycaret) (2.0.2)\n",
      "Requirement already satisfied: waitress in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from mlflow->pycaret) (2.0.0)\n",
      "Requirement already satisfied: alembic in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from mlflow->pycaret) (1.7.5)\n",
      "Requirement already satisfied: prometheus-flask-exporter in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from mlflow->pycaret) (0.18.7)\n",
      "Requirement already satisfied: gitpython>=2.1.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from mlflow->pycaret) (3.1.26)\n",
      "Requirement already satisfied: docker>=4.0.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from mlflow->pycaret) (5.0.3)\n",
      "Requirement already satisfied: tabulate>=0.7.7 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from databricks-cli>=0.8.7->mlflow->pycaret) (0.8.9)\n",
      "Requirement already satisfied: websocket-client>=0.32.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from docker>=4.0.0->mlflow->pycaret) (1.2.3)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from gitpython>=2.1.0->mlflow->pycaret) (4.0.9)\n",
      "Requirement already satisfied: smmap<6,>=3.0.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from gitdb<5,>=4.0.1->gitpython>=2.1.0->mlflow->pycaret) (5.0.0)\n",
      "Requirement already satisfied: zipp>=0.5 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from importlib-metadata!=4.7.0,>=3.7.0->mlflow->pycaret) (3.7.0)\n",
      "Requirement already satisfied: Mako in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from alembic->mlflow->pycaret) (1.1.6)\n",
      "Requirement already satisfied: greenlet!=0.4.17 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from sqlalchemy->mlflow->pycaret) (1.1.2)\n",
      "Requirement already satisfied: Werkzeug>=2.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from Flask->mlflow->pycaret) (2.0.2)\n",
      "Requirement already satisfied: itsdangerous>=2.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from Flask->mlflow->pycaret) (2.0.1)\n",
      "Requirement already satisfied: defusedxml in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.7.1)\n",
      "Requirement already satisfied: testpath in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.5.0)\n",
      "Requirement already satisfied: mistune<2,>=0.8.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.8.4)\n",
      "Requirement already satisfied: jupyterlab-pygments in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.1.2)\n",
      "Requirement already satisfied: bleach in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (4.1.0)\n",
      "Requirement already satisfied: pandocfilters>=1.4.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (1.5.0)\n",
      "Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.5.10)\n",
      "Requirement already satisfied: webencodings in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets->pycaret) (0.5.1)\n",
      "Requirement already satisfied: regex>=2021.8.3 in c:\\users\\data scientist\\appdata\\roaming\\python\\python39\\site-packages (from nltk->pycaret) (2022.1.18)\n",
      "Requirement already satisfied: funcy in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pyLDAvis->pycaret) (1.17)\n",
      "Collecting pyLDAvis\n",
      "  Using cached pyLDAvis-3.3.0.tar.gz (1.7 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'done'\n",
      "  Installing backend dependencies: started\n",
      "  Installing backend dependencies: finished with status 'done'\n",
      "    Preparing wheel metadata: started\n",
      "    Preparing wheel metadata: finished with status 'done'\n",
      "  Using cached pyLDAvis-3.2.2-py2.py3-none-any.whl\n",
      "Requirement already satisfied: future in c:\\users\\data scientist\\appdata\\roaming\\python\\python39\\site-packages (from pyLDAvis->pycaret) (0.18.2)\n",
      "Requirement already satisfied: numexpr in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pyLDAvis->pycaret) (2.8.1)\n",
      "Requirement already satisfied: statsmodels in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pyod->pycaret) (0.13.1)\n",
      "Requirement already satisfied: numba>=0.35 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from pyod->pycaret) (0.54.1)\n",
      "Requirement already satisfied: llvmlite<0.38,>=0.37.0rc1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from numba>=0.35->pyod->pycaret) (0.37.0)\n",
      "Requirement already satisfied: thinc<8.1.0,>=8.0.12 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from spacy->pycaret) (8.0.13)\n",
      "Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from spacy->pycaret) (3.3.0)\n",
      "Requirement already satisfied: typer<0.5.0,>=0.3.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from spacy->pycaret) (0.4.0)\n",
      "Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from spacy->pycaret) (1.0.6)\n",
      "Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from spacy->pycaret) (1.0.1)\n",
      "Requirement already satisfied: wasabi<1.1.0,>=0.8.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from spacy->pycaret) (0.9.0)\n",
      "Requirement already satisfied: srsly<3.0.0,>=2.4.1 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from spacy->pycaret) (2.4.2)\n",
      "Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from spacy->pycaret) (2.0.6)\n",
      "Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from spacy->pycaret) (2.0.6)\n",
      "Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from spacy->pycaret) (3.0.6)\n",
      "Requirement already satisfied: blis<0.8.0,>=0.4.0 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from spacy->pycaret) (0.7.5)\n",
      "Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.8 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from spacy->pycaret) (3.0.8)\n",
      "Requirement already satisfied: pathy>=0.3.5 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from spacy->pycaret) (0.6.1)\n",
      "Requirement already satisfied: pure-eval in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from stack-data->IPython->pycaret) (0.2.2)\n",
      "Requirement already satisfied: executing in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from stack-data->IPython->pycaret) (0.8.2)\n",
      "Requirement already satisfied: asttokens in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from stack-data->IPython->pycaret) (2.0.5)\n",
      "Requirement already satisfied: patsy>=0.5.2 in c:\\users\\data scientist\\appdata\\roaming\\python\\python39\\site-packages (from statsmodels->pyod->pycaret) (0.5.2)\n",
      "Requirement already satisfied: pynndescent>=0.5 in c:\\users\\data scientist\\.conda\\envs\\mycaret\\lib\\site-packages (from umap-learn->pycaret) (0.5.6)\n",
      "Building wheels for collected packages: wordcloud\n",
      "  Building wheel for wordcloud (setup.py): started\n",
      "  Building wheel for wordcloud (setup.py): finished with status 'error'\n",
      "  Running setup.py clean for wordcloud\n",
      "Failed to build wordcloud\n",
      "Installing collected packages: wordcloud, umap-learn, textblob, spacy, scikit-plot, pyod, pyLDAvis, pandas-profiling, mlxtend, mlflow, kmodes, imbalanced-learn, gensim, cufflinks, pycaret\n",
      "    Running setup.py install for wordcloud: started\n",
      "    Running setup.py install for wordcloud: finished with status 'error'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "      NOT AVAILABLE\n",
      "  \n",
      "    openblas_lapack_info:\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries openblas not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "      NOT AVAILABLE\n",
      "  \n",
      "    openblas_clapack_info:\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries openblas,lapack not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "      NOT AVAILABLE\n",
      "  \n",
      "    flame_info:\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries flame not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "      NOT AVAILABLE\n",
      "  \n",
      "    atlas_3_10_threads_info:\n",
      "    Setting PTATLAS=ATLAS\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries lapack_atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries tatlas,tatlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries lapack_atlas not found in C:\\\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries tatlas,tatlas not found in C:\\\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries lapack_atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\libs\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries tatlas,tatlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\libs\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries lapack_atlas not found in C:\\ProgramData\\Anaconda3\\Library\\lib\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries tatlas,tatlas not found in C:\\ProgramData\\Anaconda3\\Library\\lib\n",
      "    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>\n",
      "      NOT AVAILABLE\n",
      "  \n",
      "    atlas_3_10_info:\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries lapack_atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries satlas,satlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries lapack_atlas not found in C:\\\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries satlas,satlas not found in C:\\\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries lapack_atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\libs\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries satlas,satlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\libs\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries lapack_atlas not found in C:\\ProgramData\\Anaconda3\\Library\\lib\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries satlas,satlas not found in C:\\ProgramData\\Anaconda3\\Library\\lib\n",
      "    <class 'numpy.distutils.system_info.atlas_3_10_info'>\n",
      "      NOT AVAILABLE\n",
      "  \n",
      "    atlas_threads_info:\n",
      "    Setting PTATLAS=ATLAS\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries lapack_atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries ptf77blas,ptcblas,atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries lapack_atlas not found in C:\\\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries ptf77blas,ptcblas,atlas not found in C:\\\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries lapack_atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\libs\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries ptf77blas,ptcblas,atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\libs\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries lapack_atlas not found in C:\\ProgramData\\Anaconda3\\Library\\lib\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries ptf77blas,ptcblas,atlas not found in C:\\ProgramData\\Anaconda3\\Library\\lib\n",
      "    <class 'numpy.distutils.system_info.atlas_threads_info'>\n",
      "      NOT AVAILABLE\n",
      "  \n",
      "    atlas_info:\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries lapack_atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries f77blas,cblas,atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries lapack_atlas not found in C:\\\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries f77blas,cblas,atlas not found in C:\\\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries lapack_atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\libs\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries f77blas,cblas,atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\libs\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries lapack_atlas not found in C:\\ProgramData\\Anaconda3\\Library\\lib\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries f77blas,cblas,atlas not found in C:\\ProgramData\\Anaconda3\\Library\\lib\n",
      "    <class 'numpy.distutils.system_info.atlas_info'>\n",
      "      NOT AVAILABLE\n",
      "  \n",
      "    lapack_info:\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    customize MSVCCompiler\n",
      "      libraries lapack not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "      NOT AVAILABLE\n",
      "  \n",
      "    lapack_src_info:\n",
      "      NOT AVAILABLE\n",
      "  \n",
      "      NOT AVAILABLE\n",
      "  \n",
      "    running bdist_wheel\n",
      "    running build\n",
      "    running config_cc\n",
      "    unifing config_cc, config, build_clib, build_ext, build commands --compiler options\n",
      "    running config_fc\n",
      "    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options\n",
      "    running build_src\n",
      "    build_src\n",
      "    building py_modules sources\n",
      "    creating build\n",
      "    creating build\\src.win-amd64-3.9\n",
      "    creating build\\src.win-amd64-3.9\\numpy\n",
      "    creating build\\src.win-amd64-3.9\\numpy\\distutils\n",
      "    building library \"npymath\" sources\n",
      "    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "    C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Inumpy\\core\\src\\common -Inumpy\\core\\src -Inumpy\\core -Inumpy\\core\\src\\npymath -Inumpy\\core\\src\\multiarray -Inumpy\\core\\src\\umath -Inumpy\\core\\src\\npysort -IC:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\include -IC:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\include -IC:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\INCLUDE -IC:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\ATLMFC\\INCLUDE -IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.10240.0\\ucrt /Tc_configtest.c /Fo_configtest.obj\n",
      "    C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\LIB\\amd64 /LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\ATLMFC\\LIB\\amd64 /LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.10240.0\\ucrt\\x64 _configtest.obj /OUT:_configtest.exe\n",
      "    LINK : fatal error LNK1104: cannot open file 'kernel32.lib'\n",
      "    failure.\n",
      "    removing: _configtest.c _configtest.obj _configtest.obj.d\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-ymbyaqa2\\numpy_809048c662404d26b78660070e772f5f\\setup.py\", line 443, in <module>\n",
      "        setup_package()\n",
      "      File \"C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-ymbyaqa2\\numpy_809048c662404d26b78660070e772f5f\\setup.py\", line 435, in setup_package\n",
      "        setup(**metadata)\n",
      "      File \"C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-ymbyaqa2\\numpy_809048c662404d26b78660070e772f5f\\numpy\\distutils\\core.py\", line 171, in setup\n",
      "        return old_setup(**new_attr)\n",
      "      File \"C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\\site-packages\\setuptools\\__init__.py\", line 153, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\\distutils\\core.py\", line 148, in setup\n",
      "        dist.run_commands()\n",
      "      File \"C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\\distutils\\dist.py\", line 966, in run_commands\n",
      "        self.run_command(cmd)\n",
      "      File \"C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "        cmd_obj.run()\n",
      "      File \"C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\\site-packages\\wheel\\bdist_wheel.py\", line 299, in run\n",
      "        self.run_command('build')\n",
      "      File \"C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\\distutils\\cmd.py\", line 313, in run_command\n",
      "        self.distribution.run_command(command)\n",
      "      File \"C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "        cmd_obj.run()\n",
      "      File \"C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-ymbyaqa2\\numpy_809048c662404d26b78660070e772f5f\\numpy\\distutils\\command\\build.py\", line 47, in run\n",
      "        old_build.run(self)\n",
      "      File \"C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\\distutils\\command\\build.py\", line 135, in run\n",
      "        self.run_command(cmd_name)\n",
      "      File \"C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\\distutils\\cmd.py\", line 313, in run_command\n",
      "        self.distribution.run_command(command)\n",
      "      File \"C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "        cmd_obj.run()\n",
      "      File \"C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-ymbyaqa2\\numpy_809048c662404d26b78660070e772f5f\\numpy\\distutils\\command\\build_src.py\", line 142, in run\n",
      "        self.build_sources()\n",
      "      File \"C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-ymbyaqa2\\numpy_809048c662404d26b78660070e772f5f\\numpy\\distutils\\command\\build_src.py\", line 153, in build_sources\n",
      "        self.build_library_sources(*libname_info)\n",
      "      File \"C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-ymbyaqa2\\numpy_809048c662404d26b78660070e772f5f\\numpy\\distutils\\command\\build_src.py\", line 286, in build_library_sources\n",
      "        sources = self.generate_sources(sources, (lib_name, build_info))\n",
      "      File \"C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-ymbyaqa2\\numpy_809048c662404d26b78660070e772f5f\\numpy\\distutils\\command\\build_src.py\", line 369, in generate_sources\n",
      "        source = func(extension, build_dir)\n",
      "      File \"numpy\\core\\setup.py\", line 669, in get_mathlib_info\n",
      "        raise RuntimeError(\"Broken toolchain: cannot link a simple C program\")\n",
      "    RuntimeError: Broken toolchain: cannot link a simple C program\n",
      "    ----------------------------------------\n",
      "    ERROR: Failed building wheel for numpy\n",
      "    Running setup.py clean for numpy\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\Data Scientist\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ymbyaqa2\\\\numpy_809048c662404d26b78660070e772f5f\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\Data Scientist\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ymbyaqa2\\\\numpy_809048c662404d26b78660070e772f5f\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' clean --all\n",
      "         cwd: C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-ymbyaqa2\\numpy_809048c662404d26b78660070e772f5f\n",
      "    Complete output (10 lines):\n",
      "    Running from numpy source directory.\n",
      "  \n",
      "    `setup.py clean` is not supported, use one of the following instead:\n",
      "  \n",
      "      - `git clean -xdf` (cleans all files)\n",
      "      - `git clean -Xdf` (cleans all versioned files, doesn't touch\n",
      "                          files that aren't checked into the git repo)\n",
      "  \n",
      "    Add `--force` to your command to use it anyway if you must (unsupported).\n",
      "  \n",
      "    ----------------------------------------\n",
      "    ERROR: Failed cleaning build dir for numpy\n",
      "  Failed to build numpy\n",
      "  Installing collected packages: numpy, wheel, setuptools, scipy, Cython\n",
      "      Running setup.py install for numpy: started\n",
      "      Running setup.py install for numpy: finished with status 'error'\n",
      "      ERROR: Command errored out with exit status 1:\n",
      "       command: 'C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\Data Scientist\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ymbyaqa2\\\\numpy_809048c662404d26b78660070e772f5f\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\Data Scientist\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ymbyaqa2\\\\numpy_809048c662404d26b78660070e772f5f\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record 'C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-record-lqhie6bt\\install-record.txt' --single-version-externally-managed --prefix 'C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-build-env-zybrwu8h\\overlay' --compile --install-headers 'C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-build-env-zybrwu8h\\overlay\\Include\\numpy'\n",
      "           cwd: C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-ymbyaqa2\\numpy_809048c662404d26b78660070e772f5f\\\n",
      "      Complete output (314 lines):\n",
      "      Running from numpy source directory.\n",
      "  \n",
      "      Note: if you need reliable uninstall behavior, then install\n",
      "      with pip instead of using `setup.py install`:\n",
      "  \n",
      "        - `pip install .`       (from a git repo or downloaded source\n",
      "                                 release)\n",
      "        - `pip install numpy`   (last NumPy release on PyPi)\n",
      "  \n",
      "  \n",
      "      blas_opt_info:\n",
      "      blas_mkl_info:\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries mkl_rt not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "        NOT AVAILABLE\n",
      "  \n",
      "      blis_info:\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries blis not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "        NOT AVAILABLE\n",
      "  \n",
      "      openblas_info:\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries openblas not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "      get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'\n",
      "      customize GnuFCompiler\n",
      "      Could not locate executable g77\n",
      "      Could not locate executable f77\n",
      "      customize IntelVisualFCompiler\n",
      "      Could not locate executable ifort\n",
      "      Could not locate executable ifl\n",
      "      customize AbsoftFCompiler\n",
      "      Could not locate executable f90\n",
      "      customize CompaqVisualFCompiler\n",
      "      Could not locate executable DF\n",
      "      customize IntelItaniumVisualFCompiler\n",
      "      Could not locate executable efl\n",
      "      customize Gnu95FCompiler\n",
      "      Could not locate executable gfortran\n",
      "      Could not locate executable f95\n",
      "      customize G95FCompiler\n",
      "      Could not locate executable g95\n",
      "      customize IntelEM64VisualFCompiler\n",
      "      customize IntelEM64TFCompiler\n",
      "      Could not locate executable efort\n",
      "      Could not locate executable efc\n",
      "      customize PGroupFlangCompiler\n",
      "      Could not locate executable flang\n",
      "      don't know how to compile Fortran code on platform 'nt'\n",
      "        NOT AVAILABLE\n",
      "  \n",
      "      atlas_3_10_blas_threads_info:\n",
      "      Setting PTATLAS=ATLAS\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries tatlas not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "        NOT AVAILABLE\n",
      "  \n",
      "      atlas_3_10_blas_info:\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries satlas not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "        NOT AVAILABLE\n",
      "  \n",
      "      atlas_blas_threads_info:\n",
      "      Setting PTATLAS=ATLAS\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries ptf77blas,ptcblas,atlas not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "        NOT AVAILABLE\n",
      "  \n",
      "      atlas_blas_info:\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries f77blas,cblas,atlas not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "        NOT AVAILABLE\n",
      "  \n",
      "      accelerate_info:\n",
      "        NOT AVAILABLE\n",
      "  \n",
      "      blas_info:\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries blas not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "        NOT AVAILABLE\n",
      "  \n",
      "      blas_src_info:\n",
      "        NOT AVAILABLE\n",
      "  \n",
      "        NOT AVAILABLE\n",
      "  \n",
      "      'svnversion' is not recognized as an internal or external command,\n",
      "      operable program or batch file.\n",
      "      non-existing path in 'numpy\\\\distutils': 'site.cfg'\n",
      "      lapack_opt_info:\n",
      "      lapack_mkl_info:\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries mkl_rt not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "        NOT AVAILABLE\n",
      "  \n",
      "      openblas_lapack_info:\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries openblas not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "        NOT AVAILABLE\n",
      "  \n",
      "      openblas_clapack_info:\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries openblas,lapack not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "        NOT AVAILABLE\n",
      "  \n",
      "      flame_info:\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries flame not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "        NOT AVAILABLE\n",
      "  \n",
      "      atlas_3_10_threads_info:\n",
      "      Setting PTATLAS=ATLAS\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries lapack_atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries tatlas,tatlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries lapack_atlas not found in C:\\\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries tatlas,tatlas not found in C:\\\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries lapack_atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\libs\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries tatlas,tatlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\libs\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries lapack_atlas not found in C:\\ProgramData\\Anaconda3\\Library\\lib\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries tatlas,tatlas not found in C:\\ProgramData\\Anaconda3\\Library\\lib\n",
      "      <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>\n",
      "        NOT AVAILABLE\n",
      "  \n",
      "      atlas_3_10_info:\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries lapack_atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries satlas,satlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries lapack_atlas not found in C:\\\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries satlas,satlas not found in C:\\\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries lapack_atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\libs\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries satlas,satlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\libs\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries lapack_atlas not found in C:\\ProgramData\\Anaconda3\\Library\\lib\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries satlas,satlas not found in C:\\ProgramData\\Anaconda3\\Library\\lib\n",
      "      <class 'numpy.distutils.system_info.atlas_3_10_info'>\n",
      "        NOT AVAILABLE\n",
      "  \n",
      "      atlas_threads_info:\n",
      "      Setting PTATLAS=ATLAS\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries lapack_atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries ptf77blas,ptcblas,atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries lapack_atlas not found in C:\\\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries ptf77blas,ptcblas,atlas not found in C:\\\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries lapack_atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\libs\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries ptf77blas,ptcblas,atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\libs\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries lapack_atlas not found in C:\\ProgramData\\Anaconda3\\Library\\lib\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries ptf77blas,ptcblas,atlas not found in C:\\ProgramData\\Anaconda3\\Library\\lib\n",
      "      <class 'numpy.distutils.system_info.atlas_threads_info'>\n",
      "        NOT AVAILABLE\n",
      "  \n",
      "      atlas_info:\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries lapack_atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries f77blas,cblas,atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries lapack_atlas not found in C:\\\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries f77blas,cblas,atlas not found in C:\\\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries lapack_atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\libs\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries f77blas,cblas,atlas not found in C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\libs\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries lapack_atlas not found in C:\\ProgramData\\Anaconda3\\Library\\lib\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries f77blas,cblas,atlas not found in C:\\ProgramData\\Anaconda3\\Library\\lib\n",
      "      <class 'numpy.distutils.system_info.atlas_info'>\n",
      "        NOT AVAILABLE\n",
      "  \n",
      "      lapack_info:\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      customize MSVCCompiler\n",
      "        libraries lapack not found in ['C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\Data Scientist\\\\.conda\\\\envs\\\\mycaret\\\\libs', 'C:\\\\ProgramData\\\\Anaconda3\\\\Library\\\\lib']\n",
      "        NOT AVAILABLE\n",
      "  \n",
      "      lapack_src_info:\n",
      "        NOT AVAILABLE\n",
      "  \n",
      "        NOT AVAILABLE\n",
      "  \n",
      "      running install\n",
      "      running build\n",
      "      running config_cc\n",
      "      unifing config_cc, config, build_clib, build_ext, build commands --compiler options\n",
      "      running config_fc\n",
      "      unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options\n",
      "      running build_src\n",
      "      build_src\n",
      "      building py_modules sources\n",
      "      building library \"npymath\" sources\n",
      "      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "      C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Inumpy\\core\\src\\common -Inumpy\\core\\src -Inumpy\\core -Inumpy\\core\\src\\npymath -Inumpy\\core\\src\\multiarray -Inumpy\\core\\src\\umath -Inumpy\\core\\src\\npysort -IC:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\include -IC:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\include -IC:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\INCLUDE -IC:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\ATLMFC\\INCLUDE -IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.10240.0\\ucrt /Tc_configtest.c /Fo_configtest.obj\n",
      "      C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\LIB\\amd64 /LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\ATLMFC\\LIB\\amd64 /LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.10240.0\\ucrt\\x64 _configtest.obj /OUT:_configtest.exe\n",
      "      LINK : fatal error LNK1104: cannot open file 'kernel32.lib'\n",
      "      failure.\n",
      "      removing: _configtest.c _configtest.obj _configtest.obj.d\n",
      "      Traceback (most recent call last):\n",
      "        File \"<string>\", line 1, in <module>\n",
      "        File \"C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-ymbyaqa2\\numpy_809048c662404d26b78660070e772f5f\\setup.py\", line 443, in <module>\n",
      "          setup_package()\n",
      "        File \"C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-ymbyaqa2\\numpy_809048c662404d26b78660070e772f5f\\setup.py\", line 435, in setup_package\n",
      "          setup(**metadata)\n",
      "        File \"C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-ymbyaqa2\\numpy_809048c662404d26b78660070e772f5f\\numpy\\distutils\\core.py\", line 171, in setup\n",
      "          return old_setup(**new_attr)\n",
      "        File \"C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\\site-packages\\setuptools\\__init__.py\", line 153, in setup\n",
      "          return distutils.core.setup(**attrs)\n",
      "        File \"C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\\distutils\\core.py\", line 148, in setup\n",
      "          dist.run_commands()\n",
      "        File \"C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\\distutils\\dist.py\", line 966, in run_commands\n",
      "          self.run_command(cmd)\n",
      "        File \"C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "          cmd_obj.run()\n",
      "        File \"C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-ymbyaqa2\\numpy_809048c662404d26b78660070e772f5f\\numpy\\distutils\\command\\install.py\", line 62, in run\n",
      "          r = self.setuptools_run()\n",
      "        File \"C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-ymbyaqa2\\numpy_809048c662404d26b78660070e772f5f\\numpy\\distutils\\command\\install.py\", line 36, in setuptools_run\n",
      "          return distutils_install.run(self)\n",
      "        File \"C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\\distutils\\command\\install.py\", line 546, in run\n",
      "          self.run_command('build')\n",
      "        File \"C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\\distutils\\cmd.py\", line 313, in run_command\n",
      "          self.distribution.run_command(command)\n",
      "        File \"C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "          cmd_obj.run()\n",
      "        File \"C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-ymbyaqa2\\numpy_809048c662404d26b78660070e772f5f\\numpy\\distutils\\command\\build.py\", line 47, in run\n",
      "          old_build.run(self)\n",
      "        File \"C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\\distutils\\command\\build.py\", line 135, in run\n",
      "          self.run_command(cmd_name)\n",
      "        File \"C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\\distutils\\cmd.py\", line 313, in run_command\n",
      "          self.distribution.run_command(command)\n",
      "        File \"C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\lib\\distutils\\dist.py\", line 985, in run_command\n",
      "          cmd_obj.run()\n",
      "        File \"C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-ymbyaqa2\\numpy_809048c662404d26b78660070e772f5f\\numpy\\distutils\\command\\build_src.py\", line 142, in run\n",
      "          self.build_sources()\n",
      "        File \"C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-ymbyaqa2\\numpy_809048c662404d26b78660070e772f5f\\numpy\\distutils\\command\\build_src.py\", line 153, in build_sources\n",
      "          self.build_library_sources(*libname_info)\n",
      "        File \"C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-ymbyaqa2\\numpy_809048c662404d26b78660070e772f5f\\numpy\\distutils\\command\\build_src.py\", line 286, in build_library_sources\n",
      "          sources = self.generate_sources(sources, (lib_name, build_info))\n",
      "        File \"C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-ymbyaqa2\\numpy_809048c662404d26b78660070e772f5f\\numpy\\distutils\\command\\build_src.py\", line 369, in generate_sources\n",
      "          source = func(extension, build_dir)\n",
      "        File \"numpy\\core\\setup.py\", line 669, in get_mathlib_info\n",
      "          raise RuntimeError(\"Broken toolchain: cannot link a simple C program\")\n",
      "      RuntimeError: Broken toolchain: cannot link a simple C program\n",
      "      ----------------------------------------\n",
      "  ERROR: Command errored out with exit status 1: 'C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\Data Scientist\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ymbyaqa2\\\\numpy_809048c662404d26b78660070e772f5f\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\Data Scientist\\\\AppData\\\\Local\\\\Temp\\\\pip-install-ymbyaqa2\\\\numpy_809048c662404d26b78660070e772f5f\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record 'C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-record-lqhie6bt\\install-record.txt' --single-version-externally-managed --prefix 'C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-build-env-zybrwu8h\\overlay' --compile --install-headers 'C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-build-env-zybrwu8h\\overlay\\Include\\numpy' Check the logs for full command output.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/aa/f6/75297be19f48b7a8c2577753a3a700f98fc4db49d0e5ed3820dd8dee43d4/scikit-learn-0.23.2.tar.gz#sha256=20766f515e6cd6f954554387dfae705d93c7b544ec0e6c6a5d8e006f6f7ef480 (from https://pypi.org/simple/scikit-learn/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\python.exe' 'C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-standalone-pip-zfacx_gp\\__env_pip__.zip\\pip' install --ignore-installed --no-user --prefix 'C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-build-env-zybrwu8h\\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.28.5' 'numpy==1.13.3; python_version=='\"'\"'3.6'\"'\"' and platform_system!='\"'\"'AIX'\"'\"' and platform_python_implementation == '\"'\"'CPython'\"'\"'' 'numpy==1.14.0; python_version=='\"'\"'3.6'\"'\"' and platform_system!='\"'\"'AIX'\"'\"' and platform_python_implementation != '\"'\"'CPython'\"'\"'' 'numpy==1.14.5; python_version=='\"'\"'3.7'\"'\"' and platform_system!='\"'\"'AIX'\"'\"'' 'numpy==1.17.3; python_version>='\"'\"'3.8'\"'\"' and platform_system!='\"'\"'AIX'\"'\"'' 'numpy==1.16.0; python_version=='\"'\"'3.6'\"'\"' and platform_system=='\"'\"'AIX'\"'\"'' 'numpy==1.16.0; python_version=='\"'\"'3.7'\"'\"' and platform_system=='\"'\"'AIX'\"'\"'' 'numpy==1.17.3; python_version>='\"'\"'3.8'\"'\"' and platform_system=='\"'\"'AIX'\"'\"'' 'scipy>=0.19.1' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\Data Scientist\\\\AppData\\\\Local\\\\Temp\\\\pip-install-3lhi0a1k\\\\wordcloud_f7884d8be8154cf2b96a6d301b92d25a\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\Data Scientist\\\\AppData\\\\Local\\\\Temp\\\\pip-install-3lhi0a1k\\\\wordcloud_f7884d8be8154cf2b96a6d301b92d25a\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' bdist_wheel -d 'C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-wheel-lryu2l64'\n",
      "       cwd: C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-3lhi0a1k\\wordcloud_f7884d8be8154cf2b96a6d301b92d25a\\\n",
      "  Complete output (26 lines):\n",
      "  running bdist_wheel\n",
      "  running build\n",
      "  running build_py\n",
      "  creating build\n",
      "  creating build\\lib.win-amd64-3.9\n",
      "  creating build\\lib.win-amd64-3.9\\wordcloud\n",
      "  copying wordcloud\\color_from_image.py -> build\\lib.win-amd64-3.9\\wordcloud\n",
      "  copying wordcloud\\tokenization.py -> build\\lib.win-amd64-3.9\\wordcloud\n",
      "  copying wordcloud\\wordcloud.py -> build\\lib.win-amd64-3.9\\wordcloud\n",
      "  copying wordcloud\\wordcloud_cli.py -> build\\lib.win-amd64-3.9\\wordcloud\n",
      "  copying wordcloud\\_version.py -> build\\lib.win-amd64-3.9\\wordcloud\n",
      "  copying wordcloud\\__init__.py -> build\\lib.win-amd64-3.9\\wordcloud\n",
      "  copying wordcloud\\__main__.py -> build\\lib.win-amd64-3.9\\wordcloud\n",
      "  copying wordcloud\\stopwords -> build\\lib.win-amd64-3.9\\wordcloud\n",
      "  copying wordcloud\\DroidSansMono.ttf -> build\\lib.win-amd64-3.9\\wordcloud\n",
      "  UPDATING build\\lib.win-amd64-3.9\\wordcloud/_version.py\n",
      "  set build\\lib.win-amd64-3.9\\wordcloud/_version.py to '1.8.1'\n",
      "  running build_ext\n",
      "  building 'wordcloud.query_integral_image' extension\n",
      "  creating build\\temp.win-amd64-3.9\n",
      "  creating build\\temp.win-amd64-3.9\\Release\n",
      "  creating build\\temp.win-amd64-3.9\\Release\\wordcloud\n",
      "  C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\include -IC:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\include -IC:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\INCLUDE -IC:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\ATLMFC\\INCLUDE -IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.10240.0\\ucrt /Tcwordcloud/query_integral_image.c /Fobuild\\temp.win-amd64-3.9\\Release\\wordcloud/query_integral_image.obj\n",
      "  query_integral_image.c\n",
      "  c:\\users\\data scientist\\.conda\\envs\\mycaret\\include\\pyconfig.h(201): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory\n",
      "  error: command 'C:\\\\Program Files (x86)\\\\Microsoft Visual Studio 14.0\\\\VC\\\\BIN\\\\x86_amd64\\\\cl.exe' failed with exit code 2\n",
      "  ----------------------------------------\n",
      "  ERROR: Failed building wheel for wordcloud\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\Data Scientist\\\\AppData\\\\Local\\\\Temp\\\\pip-install-3lhi0a1k\\\\wordcloud_f7884d8be8154cf2b96a6d301b92d25a\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\Data Scientist\\\\AppData\\\\Local\\\\Temp\\\\pip-install-3lhi0a1k\\\\wordcloud_f7884d8be8154cf2b96a6d301b92d25a\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record 'C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-record-_d9qly8p\\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\Include\\wordcloud'\n",
      "         cwd: C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-install-3lhi0a1k\\wordcloud_f7884d8be8154cf2b96a6d301b92d25a\\\n",
      "    Complete output (26 lines):\n",
      "    running install\n",
      "    running build\n",
      "    running build_py\n",
      "    creating build\n",
      "    creating build\\lib.win-amd64-3.9\n",
      "    creating build\\lib.win-amd64-3.9\\wordcloud\n",
      "    copying wordcloud\\color_from_image.py -> build\\lib.win-amd64-3.9\\wordcloud\n",
      "    copying wordcloud\\tokenization.py -> build\\lib.win-amd64-3.9\\wordcloud\n",
      "    copying wordcloud\\wordcloud.py -> build\\lib.win-amd64-3.9\\wordcloud\n",
      "    copying wordcloud\\wordcloud_cli.py -> build\\lib.win-amd64-3.9\\wordcloud\n",
      "    copying wordcloud\\_version.py -> build\\lib.win-amd64-3.9\\wordcloud\n",
      "    copying wordcloud\\__init__.py -> build\\lib.win-amd64-3.9\\wordcloud\n",
      "    copying wordcloud\\__main__.py -> build\\lib.win-amd64-3.9\\wordcloud\n",
      "    copying wordcloud\\stopwords -> build\\lib.win-amd64-3.9\\wordcloud\n",
      "    copying wordcloud\\DroidSansMono.ttf -> build\\lib.win-amd64-3.9\\wordcloud\n",
      "    UPDATING build\\lib.win-amd64-3.9\\wordcloud/_version.py\n",
      "    set build\\lib.win-amd64-3.9\\wordcloud/_version.py to '1.8.1'\n",
      "    running build_ext\n",
      "    building 'wordcloud.query_integral_image' extension\n",
      "    creating build\\temp.win-amd64-3.9\n",
      "    creating build\\temp.win-amd64-3.9\\Release\n",
      "    creating build\\temp.win-amd64-3.9\\Release\\wordcloud\n",
      "    C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\include -IC:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\include -IC:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\INCLUDE -IC:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\ATLMFC\\INCLUDE -IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.10240.0\\ucrt /Tcwordcloud/query_integral_image.c /Fobuild\\temp.win-amd64-3.9\\Release\\wordcloud/query_integral_image.obj\n",
      "    query_integral_image.c\n",
      "    c:\\users\\data scientist\\.conda\\envs\\mycaret\\include\\pyconfig.h(201): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory\n",
      "    error: command 'C:\\\\Program Files (x86)\\\\Microsoft Visual Studio 14.0\\\\VC\\\\BIN\\\\x86_amd64\\\\cl.exe' failed with exit code 2\n",
      "    ----------------------------------------\n",
      "ERROR: Command errored out with exit status 1: 'C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\Data Scientist\\\\AppData\\\\Local\\\\Temp\\\\pip-install-3lhi0a1k\\\\wordcloud_f7884d8be8154cf2b96a6d301b92d25a\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\Data Scientist\\\\AppData\\\\Local\\\\Temp\\\\pip-install-3lhi0a1k\\\\wordcloud_f7884d8be8154cf2b96a6d301b92d25a\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record 'C:\\Users\\Data Scientist\\AppData\\Local\\Temp\\pip-record-_d9qly8p\\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\\Users\\Data Scientist\\.conda\\envs\\mycaret\\Include\\wordcloud' Check the logs for full command output.\n"
     ]
    }
   ],
   "source": [
    "!pip install pycaret"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'pycaret'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Input \u001b[1;32mIn [3]\u001b[0m, in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;66;03m# load dataset\u001b[39;00m\n\u001b[0;32m      2\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mpandas\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01mpd\u001b[39;00m\n\u001b[1;32m----> 3\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpycaret\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mdatasets\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m get_data\n\u001b[0;32m      4\u001b[0m data \u001b[38;5;241m=\u001b[39m get_data(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124miris\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[0;32m      5\u001b[0m \u001b[38;5;66;03m# init setup\u001b[39;00m\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'pycaret'"
     ]
    }
   ],
   "source": [
    "# load dataset\n",
    "import pandas as pd\n",
    "from pycaret.datasets import get_data\n",
    "data = get_data('iris')\n",
    "# init setup\n",
    "from pycaret.classification import *\n",
    "s = setup(data, target = 'species', session_id = 123)\n",
    "# train model\n",
    "lr = create_model('lr')\n",
    "# generate dashboard\n",
    "dashboard(lr)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "e878d85a0e670fc306315e064d60702beaa67c8127ec20d337a4720d400f0b91"
  },
  "kernelspec": {
   "display_name": "Python 3.9.7 64-bit (conda)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
